package com.cfs.dao;
import java.sql.SQLException;
import java.util.List;

import javax.sql.DataSource;

import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;
import org.apache.commons.dbutils.handlers.BeanListHandler;

import com.cfs.dto.ProtfolioDTO;

public class ProtfolioDAO {
	private DataSource ds;
	
	public ProtfolioDAO(DataSource ds) {
		this.ds = ds;
	}
	
	public List<ProtfolioDTO> getProtfolio() {
		QueryRunner run = new QueryRunner(ds);

		// Use the BeanListHandler implementation to convert all
		// ResultSet rows into a List of User JavaBeans.
		ResultSetHandler<List<ProtfolioDTO>> h = new BeanListHandler<ProtfolioDTO>(ProtfolioDTO.class);

		// Execute the SQL statement and return the results in a List of
		// User objects generated by the BeanListHandler.
		List<ProtfolioDTO> protfolio = null;
		try {
			protfolio = run.query("SELECT * FROM haisheny_user", h);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return protfolio;
	}
}
