package com.cfs.dao;
import java.sql.SQLException;
import java.util.List;

import javax.sql.DataSource;

import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;
import org.apache.commons.dbutils.handlers.BeanListHandler;

import com.cfs.dto.ProtfolioDTO;

public class ProtfolioDAO {
	private DataSource ds;
	
	public ProtfolioDAO(DataSource ds) {
		this.ds = ds;
	}
	
	public List<ProtfolioDTO> getProtfolio(int customer_id) {
		QueryRunner run = new QueryRunner(ds);

		// Use the BeanListHandler implementation to convert all
		// ResultSet rows into a List of User JavaBeans.
		ResultSetHandler<List<ProtfolioDTO>> h = new BeanListHandler<ProtfolioDTO>(ProtfolioDTO.class);

		// Execute the SQL statement and return the results in a List of
		// User objects generated by the BeanListHandler.
		List<ProtfolioDTO> protfolio = null;
		try {
			protfolio = run.query("SELECT p.customer_id as customer_id, p.fund_id as fund_id, "
					+ "f.price as price, p.shares as shares, "
					+ "f.name as fund_name, f.symbol as fund_symbol "
					+ "FROM position p, fund f "
					+ "WHERE p.customer_id=? and p.fund_id=f.fund_id", h, customer_id);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return protfolio;
	}
}
