package com.cfs.dao;
import java.sql.SQLException;
import java.util.List;

import javax.sql.DataSource;

import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;
import org.apache.commons.dbutils.handlers.BeanListHandler;

import com.cfs.dto.TransHistoryDTO;

public class TransHistoryDAO {
	private DataSource ds;
	
	public TransHistoryDAO(DataSource ds) {
		this.ds = ds;
	}
	
	public List<TransHistoryDTO> getTransHistory(int customer_id) {
		QueryRunner run = new QueryRunner(ds);

		// Use the BeanListHandler implementation to convert all
		// ResultSet rows into a List of User JavaBeans.
		ResultSetHandler<List<TransHistoryDTO>> h = new BeanListHandler<TransHistoryDTO>(TransHistoryDTO.class);

		// Execute the SQL statement and return the results in a List of
		// User objects generated by the BeanListHandler.
		List<TransHistoryDTO> trans = null;
		try {
//			trans = run.query("SELECT p.transaction_id as transaction_id, p.customer_id as customer_id, p.fund_id as fund_id, "
//					+ "p.price as price, p.shares as shares, p.amount as amount, p.execute_date as execute_date, "
//					+ "p.status as status, p.transaction_type as transaction_type, "
//					+ "f.name as fund_name, f.symbol as fund_symbol "
//					+ "FROM transaction p, fund f "
//					+ "WHERE p.customer_id=? and p.fund_id=f.fund_id", h, customer_id);
			trans = run.query("SELECT p.transaction_id as transaction_id, p.customer_id as customer_id, p.fund_id as fund_id, "
					+ "p.price as price, p.shares as shares, p.amount as amount, p.execute_date as execute_date, "
					+ "p.status as status, p.transaction_type as transaction_type, "
					+ "f.name as fund_name, f.symbol as fund_symbol "
					+ "FROM transaction p left join fund f on (p.fund_id=f.fund_id)"
					+ "WHERE p.customer_id=? order by transaction_id desc", h, customer_id);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return trans;
	}
}
